os: osx
osx_image: xcode9.4
before_install:
- sudo systemsetup -settimezone Asia/Tokyo
script:
- make archive
branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?$/"
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
